# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Write a dgCMatrix to a StreamPress (.spz) file
#' @param A A sparse matrix (dgCMatrix)
#' @param path Output file path (.spz)
#' @param use_delta Use delta prediction (better for structured data)
#' @param use_value_pred Use value prediction (for integer data)
#' @param verbose Print compression stats
#' @param precision Value precision: "auto", "fp32", "fp16", "quant8", "fp64"
#' @param row_sort Sort rows by nnz for better compression
#' @param include_transpose Also store CSC(A^T) in file
#' @return A list with compression statistics
#' @keywords internal
Rcpp_sp_write <- function(A, path, use_delta = TRUE, use_value_pred = FALSE, verbose = FALSE, precision = "auto", row_sort = FALSE, include_transpose = FALSE, chunk_cols = 2048L, obs_raw = NULL, var_raw = NULL) {
    .Call('_streampress_Rcpp_sp_write', PACKAGE = 'streampress', A, path, use_delta, use_value_pred, verbose, precision, row_sort, include_transpose, chunk_cols, obs_raw, var_raw)
}

#' @title Read a StreamPress (.spz) file into a dgCMatrix
#' @param path Input file path (.spz)
#' @param cols Optional integer vector of column indices to read (1-indexed)
#' @param reorder Whether to undo row permutation (default TRUE)
#' @param threads Number of threads for parallel decompression (0 = all available, default 0)
#' @return A sparse matrix (dgCMatrix)
#' @keywords internal
Rcpp_sp_read <- function(path, cols = NULL, reorder = TRUE, threads = 0L) {
    .Call('_streampress_Rcpp_sp_read', PACKAGE = 'streampress', path, cols, reorder, threads)
}

#' @title Read the pre-stored transpose from a v2 StreamPress (.spz) file
#' @param path Input file path (.spz)
#' @return A sparse matrix (dgCMatrix) containing CSC(A^T)
#' @keywords internal
Rcpp_sp_read_transpose <- function(path) {
    .Call('_streampress_Rcpp_sp_read_transpose', PACKAGE = 'streampress', path)
}

#' @title Get metadata from a StreamPress (.spz) file without decompressing
#' @param path Input file path (.spz)
#' @return A list with matrix metadata
#' @keywords internal
Rcpp_sp_metadata <- function(path) {
    .Call('_streampress_Rcpp_sp_metadata', PACKAGE = 'streampress', path)
}

#' @title Convert a dgCMatrix to StreamPress format (in-memory)
#' @param A A sparse matrix (dgCMatrix)
#' @param use_delta Use delta prediction
#' @param use_value_pred Use value prediction
#' @return A raw vector containing the compressed data
#' @keywords internal
Rcpp_sp_compress <- function(A, use_delta = TRUE, use_value_pred = FALSE) {
    .Call('_streampress_Rcpp_sp_compress', PACKAGE = 'streampress', A, use_delta, use_value_pred)
}

#' @title Decompress a StreamPress raw vector to a dgCMatrix
#' @param data A raw vector containing compressed StreamPress data
#' @return A sparse matrix (dgCMatrix)
#' @keywords internal
Rcpp_sp_decompress <- function(data) {
    .Call('_streampress_Rcpp_sp_decompress', PACKAGE = 'streampress', data)
}

#' @title Write a dense matrix to an SPZ v3 file
#' @param A A numeric matrix (dense)
#' @param path Output file path (.spz)
#' @param include_transpose Also store transposed panels for streaming NMF
#' @param chunk_cols Columns per chunk (default 256)
#' @param codec Compression codec: 0=RAW_FP32, 1=FP16, 2=QUANT8, 3=FP16_RANS, 4=FP32_RANS
#' @param delta Apply XOR-delta encoding before entropy coding
#' @return A list with write statistics
#' @keywords internal
Rcpp_sp_write_dense <- function(A, path, include_transpose = FALSE, chunk_cols = 256L, codec = 0L, delta = FALSE) {
    .Call('_streampress_Rcpp_sp_write_dense', PACKAGE = 'streampress', A, path, include_transpose, chunk_cols, codec, delta)
}

#' @title Read an SPZ v3 dense file into a numeric matrix
#' @param path Input file path (.spz v3)
#' @return A numeric matrix
#' @keywords internal
Rcpp_sp_read_dense <- function(path) {
    .Call('_streampress_Rcpp_sp_read_dense', PACKAGE = 'streampress', path)
}

#' @title Get metadata from an SPZ v3 dense file
#' @param path Input file path (.spz v3)
#' @return A list with file metadata
#' @keywords internal
Rcpp_sp_metadata_v3 <- function(path) {
    .Call('_streampress_Rcpp_sp_metadata_v3', PACKAGE = 'streampress', path)
}

#' @title Get available system RAM in megabytes
#' @return Double: available RAM in MB
#' @keywords internal
Rcpp_get_available_ram_mb <- function() {
    .Call('_streampress_Rcpp_get_available_ram_mb', PACKAGE = 'streampress')
}

#' @title Add transpose section to an existing v2 .spz file
#' @param path Path to the .spz v2 file
#' @param verbose Logical; print progress
#' @return Logical TRUE on success
#' @keywords internal
Rcpp_st_add_transpose <- function(path, verbose = TRUE) {
    .Call('_streampress_Rcpp_st_add_transpose', PACKAGE = 'streampress', path, verbose)
}

#' @title Serialize a data.frame to obs/var table binary format
#' @param df A data.frame
#' @return A raw vector containing the serialized table
#' @keywords internal
Rcpp_st_serialize_table <- function(df) {
    .Call('_streampress_Rcpp_st_serialize_table', PACKAGE = 'streampress', df)
}

#' @title Read obs table from a v2 .spz file
#' @param path Path to .spz file
#' @return A data.frame, or empty data.frame if no obs table
#' @keywords internal
Rcpp_st_read_obs <- function(path) {
    .Call('_streampress_Rcpp_st_read_obs', PACKAGE = 'streampress', path)
}

#' @title Read var table from a v2 .spz file
#' @param path Path to .spz file
#' @return A data.frame, or empty data.frame if no var table
#' @keywords internal
Rcpp_st_read_var <- function(path) {
    .Call('_streampress_Rcpp_st_read_var', PACKAGE = 'streampress', path)
}

