// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Rcpp_sp_write
List Rcpp_sp_write(const S4& A, const std::string& path, bool use_delta, bool use_value_pred, bool verbose, const std::string& precision, bool row_sort, bool include_transpose, int chunk_cols, Nullable<RawVector> obs_raw, Nullable<RawVector> var_raw);
RcppExport SEXP _streampress_Rcpp_sp_write(SEXP ASEXP, SEXP pathSEXP, SEXP use_deltaSEXP, SEXP use_value_predSEXP, SEXP verboseSEXP, SEXP precisionSEXP, SEXP row_sortSEXP, SEXP include_transposeSEXP, SEXP chunk_colsSEXP, SEXP obs_rawSEXP, SEXP var_rawSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    Rcpp::traits::input_parameter< bool >::type use_delta(use_deltaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_value_pred(use_value_predSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< bool >::type row_sort(row_sortSEXP);
    Rcpp::traits::input_parameter< bool >::type include_transpose(include_transposeSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_cols(chunk_colsSEXP);
    Rcpp::traits::input_parameter< Nullable<RawVector> >::type obs_raw(obs_rawSEXP);
    Rcpp::traits::input_parameter< Nullable<RawVector> >::type var_raw(var_rawSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_sp_write(A, path, use_delta, use_value_pred, verbose, precision, row_sort, include_transpose, chunk_cols, obs_raw, var_raw));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_sp_read
S4 Rcpp_sp_read(const std::string& path, Nullable<IntegerVector> cols, bool reorder, int threads);
RcppExport SEXP _streampress_Rcpp_sp_read(SEXP pathSEXP, SEXP colsSEXP, SEXP reorderSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< bool >::type reorder(reorderSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_sp_read(path, cols, reorder, threads));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_sp_read_transpose
S4 Rcpp_sp_read_transpose(const std::string& path);
RcppExport SEXP _streampress_Rcpp_sp_read_transpose(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_sp_read_transpose(path));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_sp_metadata
List Rcpp_sp_metadata(const std::string& path);
RcppExport SEXP _streampress_Rcpp_sp_metadata(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_sp_metadata(path));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_sp_compress
RawVector Rcpp_sp_compress(const S4& A, bool use_delta, bool use_value_pred);
RcppExport SEXP _streampress_Rcpp_sp_compress(SEXP ASEXP, SEXP use_deltaSEXP, SEXP use_value_predSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const S4& >::type A(ASEXP);
    Rcpp::traits::input_parameter< bool >::type use_delta(use_deltaSEXP);
    Rcpp::traits::input_parameter< bool >::type use_value_pred(use_value_predSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_sp_compress(A, use_delta, use_value_pred));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_sp_decompress
S4 Rcpp_sp_decompress(const RawVector& data);
RcppExport SEXP _streampress_Rcpp_sp_decompress(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const RawVector& >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_sp_decompress(data));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_sp_write_dense
List Rcpp_sp_write_dense(const NumericMatrix& A, const std::string& path, bool include_transpose, int chunk_cols, int codec, bool delta);
RcppExport SEXP _streampress_Rcpp_sp_write_dense(SEXP ASEXP, SEXP pathSEXP, SEXP include_transposeSEXP, SEXP chunk_colsSEXP, SEXP codecSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    Rcpp::traits::input_parameter< bool >::type include_transpose(include_transposeSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_cols(chunk_colsSEXP);
    Rcpp::traits::input_parameter< int >::type codec(codecSEXP);
    Rcpp::traits::input_parameter< bool >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_sp_write_dense(A, path, include_transpose, chunk_cols, codec, delta));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_sp_read_dense
NumericMatrix Rcpp_sp_read_dense(const std::string& path);
RcppExport SEXP _streampress_Rcpp_sp_read_dense(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_sp_read_dense(path));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_sp_metadata_v3
List Rcpp_sp_metadata_v3(const std::string& path);
RcppExport SEXP _streampress_Rcpp_sp_metadata_v3(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_sp_metadata_v3(path));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_get_available_ram_mb
double Rcpp_get_available_ram_mb();
RcppExport SEXP _streampress_Rcpp_get_available_ram_mb() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(Rcpp_get_available_ram_mb());
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_st_add_transpose
bool Rcpp_st_add_transpose(const std::string& path, bool verbose);
RcppExport SEXP _streampress_Rcpp_st_add_transpose(SEXP pathSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_st_add_transpose(path, verbose));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_st_serialize_table
RawVector Rcpp_st_serialize_table(const DataFrame& df);
RcppExport SEXP _streampress_Rcpp_st_serialize_table(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const DataFrame& >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_st_serialize_table(df));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_st_read_obs
DataFrame Rcpp_st_read_obs(const std::string& path);
RcppExport SEXP _streampress_Rcpp_st_read_obs(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_st_read_obs(path));
    return rcpp_result_gen;
END_RCPP
}
// Rcpp_st_read_var
DataFrame Rcpp_st_read_var(const std::string& path);
RcppExport SEXP _streampress_Rcpp_st_read_var(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(Rcpp_st_read_var(path));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_streampress_Rcpp_sp_write", (DL_FUNC) &_streampress_Rcpp_sp_write, 11},
    {"_streampress_Rcpp_sp_read", (DL_FUNC) &_streampress_Rcpp_sp_read, 4},
    {"_streampress_Rcpp_sp_read_transpose", (DL_FUNC) &_streampress_Rcpp_sp_read_transpose, 1},
    {"_streampress_Rcpp_sp_metadata", (DL_FUNC) &_streampress_Rcpp_sp_metadata, 1},
    {"_streampress_Rcpp_sp_compress", (DL_FUNC) &_streampress_Rcpp_sp_compress, 3},
    {"_streampress_Rcpp_sp_decompress", (DL_FUNC) &_streampress_Rcpp_sp_decompress, 1},
    {"_streampress_Rcpp_sp_write_dense", (DL_FUNC) &_streampress_Rcpp_sp_write_dense, 6},
    {"_streampress_Rcpp_sp_read_dense", (DL_FUNC) &_streampress_Rcpp_sp_read_dense, 1},
    {"_streampress_Rcpp_sp_metadata_v3", (DL_FUNC) &_streampress_Rcpp_sp_metadata_v3, 1},
    {"_streampress_Rcpp_get_available_ram_mb", (DL_FUNC) &_streampress_Rcpp_get_available_ram_mb, 0},
    {"_streampress_Rcpp_st_add_transpose", (DL_FUNC) &_streampress_Rcpp_st_add_transpose, 2},
    {"_streampress_Rcpp_st_serialize_table", (DL_FUNC) &_streampress_Rcpp_st_serialize_table, 1},
    {"_streampress_Rcpp_st_read_obs", (DL_FUNC) &_streampress_Rcpp_st_read_obs, 1},
    {"_streampress_Rcpp_st_read_var", (DL_FUNC) &_streampress_Rcpp_st_read_var, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_streampress(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
